# Generated by Django 4.2.7 on 2023-12-19 23:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher_msg',
            new_name='message',
        ),
        migrations.DeleteModel(
            name='student_msg',
        ),
    ]
