# Generated by Django 4.2.7 on 2023-12-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_teacher_msg_message_delete_student_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
