# Generated by Django 4.2.7 on 2023-12-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
