# Generated by Django 4.2.7 on 2023-12-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_teacherprofile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
    ]
