# Generated by Django 4.2.7 on 2023-12-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_teacherprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
